import type { Platform, StatItem } from "@/types/rates";

export const stats: StatItem[] = [
  {
    label: "Fast Buy Rate",
    value: "₦1,658",
    subValue: "Per $1.00",
    icon: "TrendingUp",
    color: "emerald",
  },
  {
    label: "Sell-out Rate",
    value: "₦1,672",
    subValue: "Per $1.00",
    icon: "TrendingDown",
    color: "blue",
  },
  {
    label: "Average Rate",
    value: "₦1,650",
    subValue: "Weekly average",
    icon: "BarChart3",
    color: "fuchsia",
  },
  {
    label: "24h Volume",
    value: "$10.5k",
    trend: "up",
    trendValue: "+$1.2k",
    icon: "Activity",
    color: "amber",
  },
];

export const platforms: Platform[] = [
  {
    id: "wise",
    name: "Wise",
    logo: "https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=64&h=64&fit=crop&q=80",
    rating: 4.9,
    reviews: 124,
    isPopular: true,
    buyRate: 1658,
    sellRate: 1680,
    buyTrend: "up",
    sellTrend: "down",
    buyChangePercent: 1.2,
    sellChangePercent: 0.8,
    processingTime: "0-5 Minutes",
    minMaxLimit: "$500 - Unlimited",
    updatedAt: "2 Minutes Ago",
  },
  {
    id: "zelle",
    name: "Zelle",
    logo: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=64&h=64&fit=crop&q=80",
    rating: 4.8,
    reviews: 98,
    isPopular: true,
    buyRate: 1655,
    sellRate: 1685,
    buyTrend: "up",
    sellTrend: "up",
    buyChangePercent: 1.5,
    sellChangePercent: 1.2,
    processingTime: "2-5 Minutes",
    minMaxLimit: "$100 - Unlimited",
    updatedAt: "2 Minutes Ago",
  },
  {
    id: "cashapp",
    name: "CashApp",
    logo: "https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=64&h=64&fit=crop&q=80",
    rating: 4.8,
    reviews: 156,
    isPopular: false,
    buyRate: 1652,
    sellRate: 1682,
    buyTrend: "up",
    sellTrend: "down",
    buyChangePercent: 2.1,
    sellChangePercent: 0.5,
    processingTime: "2-5 Minutes",
    minMaxLimit: "$20 - $5,000",
    updatedAt: "2 Minutes Ago",
  },
  {
    id: "paypal",
    name: "PayPal",
    logo: "https://images.unsplash.com/photo-1614680376408-81e91ffe3db7?w=64&h=64&fit=crop&q=80",
    rating: 3.8,
    reviews: 245,
    isPopular: true,
    buyRate: 1650,
    sellRate: 1680,
    buyTrend: "up",
    sellTrend: "down",
    buyChangePercent: 2.2,
    sellChangePercent: 0.3,
    processingTime: "0-10 Minutes",
    minMaxLimit: "$10 - Unlimited",
    updatedAt: "2 Minutes Ago",
  },
  {
    id: "venmo",
    name: "Venmo",
    logo: "https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=64&h=64&fit=crop&q=80",
    rating: 4.7,
    reviews: 87,
    isPopular: false,
    buyRate: 1648,
    sellRate: 1678,
    buyTrend: "up",
    sellTrend: "down",
    buyChangePercent: 1.2,
    sellChangePercent: 0.1,
    processingTime: "15-20 Minutes",
    minMaxLimit: "$50 - $1,500",
    updatedAt: "2 Minutes Ago",
  },
];
